name 'dsi-mq'
maintainer 'Leonard TAVAE'
maintainer_email 'leonard.tavae@informatique.gov.pf'
license 'Apache 2.0'
description 'Installs/Configures dsi-mq'
long_description 'Installs/Configures dsi-mq'
version '0.1.0'

depends 'rabbitmq'
depends 'keepalived'
